<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CommentaireTeam_View {

	/**
	 * 
	 * @var CommentaireTeam
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var CommentaireTeam_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param CommentaireTeam $model 
	 * @param CommentaireTeam_Controller $controller 
	 * @return void
	 */

	public final  function __construct(CommentaireTeam $model, CommentaireTeam_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherCommentaire() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireCommentaire() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireSupprimerCommentaire() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return html
	 */

	public final  function FormulaireEditerCommentaire($listeDonnee) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireReponse() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherTousCommentaire() {

	}


}
?>