<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ContenuMenu_View {

	/**
	 * 
	 * @var ContenuMenu
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var ContenuMenu_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param ContenuMenu $model 
	 * @param ContenuMenu_Controller $controller 
	 * @return void
	 */

	public final  function __construct(ContenuMenu $model, ContenuMenu_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoMenu() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireChangerPosition() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireAjouterLien() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireSupprimerLien() {

	}


}
?>