<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class EditeurHTML_View {

	/**
	 * 
	 * @var EditeurHTML
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var EditeurHTML_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param EditeurHTML $model 
	 * @param EditeurHTML_Controller $controller 
	 * @return void
	 */

	public final  function __construct(EditeurHTML $model, EditeurHTML_Controller $controller) {

	}


	/**
	 * Appel de la méthode dans ContenuHTML
	 * @access public
	 * @return html
	 */

	public final  function FormulaireContenuHTML() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherElementsContenuHTML() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherEmplacementVide() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherEmplacementOccupés() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireEmplacementVide() {

	}


}
?>