<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Facture_View {

	/**
	 * 
	 * @var Facture
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Facture_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Facture $model 
	 * @param Facture_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Facture $model, Facture_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AffichierFacture() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function AfficherEmplacementFichier() {

	}


}
?>