<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class JeuEnSimulation_View {

	/**
	 * 
	 * @var JeuEnSimulation
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var JeuEnSimulation_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param JeuEnSimulation $model 
	 * @param JeuEnSimulation_Controller $controller 
	 * @return void
	 */

	public final  function __construct(JeuEnSimulation $model, JeuEnSimulation_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoSimulation() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherObjetSimule() {

	}


	/**
	 * Formulaire de filtre
	 * @access public
	 * @return html
	 */

	public final  function AfficherHistoriqueSimulation() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherSimulationUtilisateur() {

	}


}
?>