<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Not_ConditionNotification_View {

	/**
	 * 
	 * @var Not_ConditionNotification
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Not_ConditionNotification_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Not_ConditionNotification $model 
	 * @param Not_ConditionNotification_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Not_ConditionNotification $model, Not_ConditionNotification_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherEditeurCondition() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireAutorisationNotification() {

	}


}
?>