<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Portefeuille_View {

	/**
	 * 
	 * @var Portefeuille
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Portefeuille_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Portefeuille $model 
	 * @param Portefeuille_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Portefeuille $model, Portefeuille_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherPortefeuille() {

	}


}
?>