<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategieUtilisateur_View {

	/**
	 * 
	 * @var StrategieUtilisateur
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var StrategieUtilisateur_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param StrategieUtilisateur $model 
	 * @param StrategieUtilisateur_Controller $controller 
	 * @return void
	 */

	public final  function __construct(StrategieUtilisateur $model, StrategieUtilisateur_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherProprietaire() {

	}


	/**
	 * Ne pas oublié le bouton pour pouvoir ajouter une technique en favorite.
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoStratégie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireEditionStategieUtilisateur() {

	}


	/**
	 * @access public
	 * @param int $idStrategie 
	 * @return html
	 */

	public final  function AfficherIconeFavoris($idStrategie) {

	}


	/**
	 * @access public
	 * @param int $idStrategie 
	 * @return html
	 */

	public final  function FormulaireStrategieFavorite($idStrategie) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStrategiesUtilisateur() {

	}


}
?>