<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Strategie_View {

	/**
	 * 
	 * @var Strategie
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Strategie_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Strategie $model 
	 * @param Strategie_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Strategie $model, Strategie_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStatistiqueStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStratistiqueDetaille() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherUtilisationStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireStatistiqueStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireInfoStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function EditeurStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireNouvelleStrategie() {

	}


}
?>