<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TableauDesGains_View {

	/**
	 * 
	 * @var TableauDesGains
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var TableauDesGains_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param TableauDesGains $model 
	 * @param TableauDesGains_Controller $controller 
	 * @return void
	 */

	public final  function __construct(TableauDesGains $model, TableauDesGains_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherLigneGain() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireEditionLigne() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherTableGain() {

	}


}
?>