<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Tirage_View {

	/**
	 * 
	 * @var Tirage
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Tirage_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Tirage $model 
	 * @param Tirage_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Tirage $model, Tirage_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherTirage() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireEditionTirage() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireNouveauTirage() {

	}


	/**
	 * filtre sur période y compris tous
	 * @access public
	 * @return html
	 */

	public final  function AfficherPlusieursTirages() {

	}


}
?>