<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Utilisateur_View {

	/**
	 * 
	 * @var Facture
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Facture_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Facture $model 
	 * @param Facture_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Facture $model, Facture_Controller $controller) {

	}


	/**
	 * infos personnelles + cagnotte + récapitulatif des gains
	 * @access public
	 * @return html
	 */

	public final  function AfficherAccueilUtilisateur() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return html
	 */

	public final  function AfficherInfoUtilisateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param Utilisateur $utilisateur 
	 * @return html
	 */

	public final  function FormulaireEditerUtilisateur(Utilisateur $utilisateur) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireNouvelUtilisateur() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireTypeUtilisateur() {

	}


}
?>