<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Abonnement_Controller {

	/**
	 * 
	 * @var Abonnement
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Abonnement $model 
	 * @return void
	 */

	public final  function __construct(Abonnement $model) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouvelAbonnement($listeDonnee) {

	}


	/**
	 * @access public
	 * @param date $dateFinAbonnement 
	 * @param string $categorieAbonnement 
	 * @return void
	 */

	public final  function EnregistrerReabonnement(date $dateFinAbonnement, $categorieAbonnement) {

	}


	/**
	 * @access public
	 * @param string $categorieAbonnement 
	 * @return void
	 */

	public final  function ChangerLimite($categorieAbonnement) {

	}


	/**
	 * @access public
	 * @param string $nouvelleCategorie 
	 * @return void
	 */

	public final  function ChangerCategorie($nouvelleCategorie) {

	}


}
?>