<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class AbonnementUtilisateur_Controller {

	/**
	 * 
	 * @var Facture
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Facture $model 
	 * @return void
	 */

	public final  function __construct(Facture $model) {

	}


	/**
	 * @access public
	 * @param date $nouvelleDate 
	 * @return void
	 */

	public final  function ChangerDateFinValidite(date $nouvelleDate) {

	}


}
?>