<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CalculStatistique_Controller {

	/**
	 * 
	 * @var CalculStatistique
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param CalculStatistique $model 
	 * @return void
	 */

	public final  function __construct(CalculStatistique $model) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function RecalculerStatistique() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function CalculerStatistiqueGain() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function CalculerStatistiqueGlobale() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function CalculerStatistiqueRecente() {

	}


}
?>