<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CompteCouverture_Controller {

	/**
	 * 
	 * @var CompteCouverture
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param CompteCouverture $model 
	 * @return void
	 */

	public final  function __construct(CompteCouverture $model) {

	}


	/**
	 * @access public
	 * @param float $somme positif ou négatif
	 */

	public final  function ChangerMontantActuel($somme) {

	}


	/**
	 * @access public
	 * @param float $somme positif ou négatif
	 * @return void
	 */

	public final  function ChangerCreditCirculant($somme) {

	}


	/**
	 * @access public
	 * @param float $somme Positif ou négatif
	 * @return void
	 */

	public final  function ChangerCreditTotal($somme) {

	}


	/**
	 * positif ou négatif
	 * @access public
	 * @return float
	 */

	public final  function ComparerMontantActuelCouverture() {

	}


}
?>