<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ContenuMenu_Controller {

	/**
	 * 
	 * @var ContenuMenu
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param ContenuMenu $model 
	 * @return void
	 */

	public final  function __construct(ContenuMenu $model) {

	}


	/**
	 * @access public
	 * @param LienSite $lienSite 
	 * @return html
	 */

	public final  function RechercherCodeLien(LienSite $lienSite) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function ConstruireCodeMenu() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerContenuMenu() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function SupprimerContenuMenu() {

	}


}
?>