<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class EditeurHTML_Controller {

	/**
	 * 
	 * @var EditeurHTML
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param EditeurHTML $model 
	 * @return void
	 */

	public final  function __construct(EditeurHTML $model) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function RechercherContenuPrincipal() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function RenseignerEmplacementLibres() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function RenseignerEmplacementOccupés() {

	}


	/**
	 * @access public
	 * @return string[]
	 */

	public final  function RechercherTousEmplacements() {

	}


	/**
	 * @access public
	 * @return ContenuHTML[]
	 */

	public final  function ListerContenuHTMLExistant() {

	}


}
?>