<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Facture_Controller {

	/**
	 * 
	 * @var Facture
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Facture $model 
	 * @return void
	 */

	public final  function __construct(Facture $model) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function GenererFichierFacture() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function GenererNumeroFacture() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouvelleFacture($listeDonnee) {

	}


}
?>