<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Jeu_Controller {

	/**
	 * 
	 * @var Jeu
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Jeu $model 
	 * @return void
	 */

	public final  function __construct(Jeu $model) {

	}


	/**
	 * @access public
	 * @param MessageJeu[] $messageJeu 
	 * @return void
	 */

	public final  function ChangerListeMessageJeu(MessageJeu[] $messageJeu) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ReinitialiserMessageResultat() {

	}


	/**
	 * @access public
	 * @param array $nouveauResultat 
	 * @return void
	 */

	public final  function AjouterListeResultat($nouveauResultat) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ComposerMessageResultat() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function CalculerGainFinal() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function CalculerDepenseFinale() {

	}


	/**
	 * @access public
	 */

	public final  function Rechercher() {

	}


}
?>