<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class JeuEnSimulation_Controller {

	/**
	 * 
	 * @var JeuEnSimulation
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param JeuEnSimulation $model 
	 * @return void
	 */

	public final  function __construct(JeuEnSimulation $model) {

	}


	/**
	 * @access public
	 * @param MessageResultat[] $messageResultat 
	 * @return void
	 */

	public final  function EnregistrerMessageResultat(MessageResultat[] $messageResultat) {

	}


	/**
	 * @access public
	 * @param MessageJeu[] $messageJeu 
	 * @return void
	 */

	public final  function EnreigstrerMessageJeu(MessageJeu[] $messageJeu) {

	}


	/**
	 * @access public
	 * @param datetime $dateJeu 
	 * @return void
	 */

	public final  function CalculStatistique(datetime $dateJeu) {

	}


	/**
	 * @access public
	 * @param CalculStatistique $statistique 
	 * @return void
	 */

	public final  function EnregistrerStatistique(CalculStatistique $statistique) {

	}


	/**
	 * @access public
	 * @param string $typeObjet Technique composée / Stratégie
	 * @param int $idObjet 
	 * @return void
	 */

	public final  function SupprimerSimulation($typeObjet, $idObjet) {

	}


	/**
	 * @access public
	 * @param int $utilisateur 
	 * @return array(TechniqueComposee[], Strategie[])
	 */

	public final  function RechercherJeuxSimules($utilisateur = false) {

	}


	/**
	 * @access public
	 * @param string $typeObjet Technique composée / Stratégie
	 * @param int $idObjet 
	 * @return array(Technique[], Strategie[])
	 */

	public final  function RechercherHistorique($typeObjet, $idObjet) {

	}


	/**
	 * @access public
	 * @param MessageJeu $messageJeu 
	 * @param string $objType Technique composée / Stratégie
	 * @param int $idObjet 
	 * @return void
	 */

	public final  function EnregistrerNouvelleSimulation(MessageJeu $messageJeu, $objType, $idObjet) {

	}


}
?>