<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class LienSite_Controller {

	/**
	 * 
	 * @var LienSite
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param LienSite $model 
	 * @return void
	 */

	public final  function __construct(LienSite $model) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function GenererCodeHtml() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerLien($listeDonnee) {

	}


	/**
	 * @access public
	 * @param int $idLien 
	 * @return void
	 */

	public final  function SupprimerLien($idLien) {

	}


}
?>