<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Not_ConditionNotification_Controller {

	/**
	 * 
	 * @var Not_ConditionNotification
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Not_ConditionNotification $model 
	 * @return void
	 */

	public final  function __construct(Not_ConditionNotification $model) {

	}


	/**
	 * @access public
	 * @return Not_ConditionNotification[]
	 */

	public final  function RechercherToutesConditions() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerConditionNotification() {

	}


}
?>