<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ResultatTeam_Controller {

	/**
	 * 
	 * @var ResultatTeam
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param ResultatTeam $model 
	 * @return void
	 */

	public final  function __construct(ResultatTeam $model) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerResultat($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherStatistiqueDernierJeu() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherStatistiqueTousJeux() {

	}


	/**
	 * @access public
	 * @param int $idUtilisateur 
	 * @return array
	 */

	public final  function RechercherStatistiqueUnMembre($idUtilisateur) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function CreerResultatTeam() {

	}


}
?>