<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Simulateur_Controller {

	/**
	 * 
	 * @var Simulateur
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Simulateur $model 
	 * @return void
	 */

	public final  function __construct(Simulateur $model) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DemarrerJeuEnCours() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DemarrerJeuEnSimulation() {

	}


	/**
	 * @access public
	 * @param  $listeDonnee 
	 * @return bool
	 */

	public final  function TesterFormSimulationManuelle($listeDonnee) {

	}


	/**
	 * @access public
	 * @param  $listeDonnee 
	 * @return void
	 */

	public final  function DemarrerSimulationManuelle($listeDonnee) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DemarrerSimulationGlobale() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function CompleterStatistiqueEnCoursEtSimulation() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherStatistiqueStrategieEtTechnique() {

	}


}
?>