<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TCConditionGrille_Controller {

	/**
	 * 
	 * @var TCConditionGrille
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param TCConditionGrille $model 
	 * @return void
	 */

	public final  function __construct(TCConditionGrille $model) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DecomposerMessageDemande() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ComposerGrilleFormatee() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ComposerTexteDescription() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public abstract  function CalculerNombreGrille() ;

	/**
	 * @access public
	 * @return TCConditionGrille[]
	 */

	public final  function RechercherConditionsGrille() {

	}


}
?>