<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Team_Controller {

	/**
	 * 
	 * @var Team
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Team $model 
	 * @return void
	 */

	public final  function __construct(Team $model) {

	}


	/**
	 * @access public
	 * @param Joueur $nouveauJoueur 
	 * @return void
	 */

	public final  function ValiderInscription(Joueur $nouveauJoueur) {

	}


	/**
	 * @access public
	 * @param string $nouveauNom 
	 * @return bool
	 */

	public final  function TesterFormulaireChangementNom($nouveauNom) {

	}


	/**
	 * @access public
	 * @param string $nouveauNom 
	 * @return void
	 */

	public final  function EnregistrerChangementNom($nouveauNom) {

	}


	/**
	 * @access public
	 * @param int $objectifFinancier 
	 * @return bool
	 */

	public final  function TesterFormObjectifFinancier($objectifFinancier) {

	}


	/**
	 * @access public
	 * @param int $objectifFinancier 
	 * @return void
	 */

	public final  function EnregistrerObjectifFinancier($objectifFinancier) {

	}


	/**
	 * @access public
	 * @param Abonnement $abonnement 
	 * @return void
	 */

	public final  function changerAbonnement(Abonnement $abonnement) {

	}


	/**
	 * @access public
	 * @return Team[]
	 */

	public final  function RechercherToutesEquipes() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return bool
	 */

	public final  function TesterFormNouvelleTeam($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouvelleTeam($listeDonnee) {

	}


}
?>