<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Tirage_Controller {

	/**
	 * 
	 * @var Tirage
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Tirage $model 
	 * @return void
	 */

	public final  function __construct(Tirage $model) {

	}


	/**
	 * numTirage, dateJeu, listeNum, multiplicateur
	 * @access public
	 * @return MessageResultat
	 */

	public final  function ComposerTableauResultat() {

	}


	/**
	 * @access public
	 * @param datetime $dateTirageDebut 
	 * @param datetime $dateTirageFin 
	 * @return Tirage[]
	 */

	public final  function RechercherTirage(datetime $dateTirageDebut, datetime $dateTirageFin) {

	}


	/**
	 * @access public
	 * @return Tirage[]
	 */

	public final  function RechecherTousTirages() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNumeroDernierTirage() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateDernierTirage() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouveauTirage($listeDonnee) {

	}


	/**
	 * Envoyer le tableau de résultats
	 * @access public
	 * @return void
	 */

	public final  function ObservateurTirage() {

	}


}
?>