<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Versement_Controller {

	/**
	 * 
	 * @var Versement
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Versement $model 
	 * @return void
	 */

	public final  function __construct(Versement $model) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function GenererFichierVersement() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function GenererNumeroVersement() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouveauVersement($listeDonnee) {

	}


	/**
	 * @access public
	 * @param int $credit 
	 * @return void
	 */

	public final  function DemanderVersement($credit) {

	}


}
?>