<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Abonnement_View {

	/**
	 * 
	 * @var Abonnement
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Abonnement_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Abonnement $model 
	 * @param Abonnement_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Abonnement $model, Abonnement_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoAbonnement() {

	}


	/**
	 * - Compte utilisateur
- Formule abonnement
- Crédit supplémentaire
	 * @access public
	 * @return html
	 */

	public final  function FormulaireCommande() {

	}


	/**
	 * - Compte utili.
- Formule
- Crédit supl.
	 * @access public
	 * @return html
	 */

	public final  function FormulaireReabonnement() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireCreditSuplementaire() {

	}


}
?>