<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class AbonnementUtilisateur {

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $identifiant;

	/**
	 * 
	 * @var Utilisateur
	 * @access public
	 */
	public  $utilisateur;

	/**
	 * 
	 * @var Abonnement
	 * @access public
	 */
	public  $abonnement;

	/**
	 * 
	 * @var date
	 * @access public
	 */
	public  $dateFinValide;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInfoAbonnement() {

	}


}
?>