<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Abonnement {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $Identifiant;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $titre;

	/**
	 * 
	 * @var array
	 * @access private
	 */
	private  $categorie = ("Light", "Silver", "Gold", "Platine");

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $limiteAccessStrategie;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $limiteUtilisationPublic;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $limiteConstructionStratégie;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $limiteCreationTeam;


	/**
	 * @access public
	 * @param array $listeDonne 
	 * @return void
	 */

	public final  function __construct($listeDonne) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInfoAbonnement() {

	}


}
?>