<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CalculStatistique_View {

	/**
	 * 
	 * @var CalculStatistique
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var CalculStatistique_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param CalculStatistique $model 
	 * @param CalculStatistique_Controller $controller 
	 * @return void
	 */

	public final  function __construct(CalculStatistique $model, CalculStatistique_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherTouteStatistique() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherUneStatistique() {

	}


}
?>