<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CalculStatistique {

	/**
	 * Strategie ou Technique composée
	 * @var string
	 * @access private
	 */
	private  $typeObjet;

	/**
	 * en cours ou en simulation
	 * @var string
	 * @access private
	 */
	private  $typeJeu;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiantObjet;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebutCalcul;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateFinCalcul;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombrePartieTestee;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombrePartieJouee;

	/**
	 * Voir document MVC KBot + array(Statistique générale, récente, de gain)
	 * @var array
	 * @access private
	 */
	private  $tableauStatistique;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherStatistiqueGain() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherStatistiqueGlobale() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherStatistiqueRécente() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInformations() {

	}


}
?>