<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CommentaireTeam {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var Team
	 * @access private
	 */
	private  $team;

	/**
	 * 
	 * @var Joueur
	 * @access private
	 */
	private  $joueurProprietaire;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateCommentaire;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $Commentaire;

	/**
	 * Visible, Banni
	 * @var string
	 * @access private
	 */
	private  $statut;

	/**
	 * 
	 * @var Commentaire[]
	 * @access private
	 */
	private  $commentaireRetour;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Joueur
	 */

	public final  function RechercherProprietaire() {

	}


	/**
	 * @access public
	 * @return Commentaire[]
	 */

	public final  function RechercherCommentaireRetour() {

	}


	/**
	 * @access public
	 * @return Team
	 */

	public final  function RechercherTeam() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTitre() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDate() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherCommentaire() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function rechercherStatut() {

	}


}
?>