<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CommentaireTeam_Controller {

	/**
	 * 
	 * @var CommentaireTeam
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param CommentaireTeam $model 
	 * @return void
	 */

	public final  function __construct(CommentaireTeam $model) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return bool
	 */

	public final  function TesterFormCommentaire($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerCommentaire($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return bool
	 */

	public final  function TesterFormEditerCommentaire($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function ChangerCommentaire($listeDonnee) {

	}


	/**
	 * @access public
	 * @param int $idCommentaire Supprimer également les enfants.
	 * @return void
	 */

	public final  function SupprimerCommentaire($idCommentaire) {

	}


	/**
	 * @access public
	 * @param string $nouveauStatut 
	 * @return void
	 */

	public final  function ChangerStatut($nouveauStatut) {

	}


	/**
	 * Ordonné par date
	 * @access public
	 * @return Commentaire[]
	 */

	public final  function RechercherTousCommentaire() {

	}


}
?>