<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CompteEntreprise {

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $montant;


	/**
	 * @access public
	 * @param  $ 
	 * @return void
	 */

	public final  function __construct($) {

	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function Rechercher le montant() {

	}


}
?>