<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CompteCouverture {

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $montantActuel;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $montantCouverture;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $creditTotal;


	/**
	 * @access public
	 * @return void
	 */

	public final  function __construct() {

	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function RechercherMontantActuel() {

	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function RechercherMontantCouverture() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherCreditCircultant() {

	}


}
?>