<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CompteEntreprise_Controller {

	/**
	 * 
	 * @var CompteEntreprise
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param CompteEntreprise $model 
	 * @return void
	 */

	public final  function __construct(CompteEntreprise $model) {

	}


	/**
	 * @access public
	 * @param float $nouveauMontant 
	 * @return void
	 */

	public final  function changerMontant($nouveauMontant) {

	}


}
?>