<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ContenuHTML_View {

	/**
	 * 
	 * @var ContenuHTML
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var ContenuHTML_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param ContenuHTML $model 
	 * @param ContenuHTML_Controller $controller 
	 * @return void
	 */

	public final  function __construct(ContenuHTML $model, ContenuHTML_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoContenu() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireChangerEmplacement() {

	}


	/**
	 * Créer, ajouter ou éditer un Contenu HTML
	 * @access public
	 * @return html
	 */

	public final  function FormulaireCodeHTML() {

	}


}
?>