<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ContenuMenu {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $position = <%Menu principal%>;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $titre;

	/**
	 * Ordre d'affichage du lien et Code HTML
	 * @var array
	 * @access private
	 */
	private  $tableauLien;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherPosition() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTitre() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherTableauLien() {

	}


}
?>