<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ContenuHTML_Controller {

	/**
	 * 
	 * @var ContenuHTML
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param ContenuHTML $model 
	 * @return void
	 */

	public final  function __construct(ContenuHTML $model) {

	}


	/**
	 * @access public
	 * @param string $codeHTML 
	 * @return void
	 */

	public final  function EnregistrerCodeHTML($codeHTML) {

	}


	/**
	 * @access public
	 * @param string $nouvelEmplacement 
	 * @return void
	 */

	public final  function ChangerEmplacement($nouvelEmplacement) {

	}


	/**
	 * @access public
	 * @param bool $public 
	 * @return void
	 */

	public final  function ChangerTypeAffichage($public = false) {

	}


	/**
	 * @access public
	 * @param bool $etreActif 
	 * @return void
	 */

	public final  function ChangerStatutActif($etreActif) {

	}


	/**
	 * @access public
	 * @param  $ContenuHTML 
	 * @return void
	 */

	public final  function CopierCodeHTML($ContenuHTML) {

	}


	/**
	 * @access public
	 * @param int $idContenuHTML 
	 * @return void
	 */

	public final  function SupprimerContenu($idContenuHTML) {

	}


}
?>