<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class JeuEnSimulation {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * Stratégie ou Technique composées
	 * @var string
	 * @access private
	 */
	private  $typeObjet;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $idObjet;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateJeu;

	/**
	 * 
	 * @var MessageJeu[]
	 * @access private
	 */
	private  $messageJeu;

	/**
	 * 
	 * @var MessageResultat[]
	 * @access private
	 */
	private  $messageResultat;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $etreJeuManuel;

	/**
	 * 
	 * @var CalculStatistique
	 * @access private
	 */
	private  $statistique;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param MessageResultat $messageResultat 
	 * @return void
	 */

	public final  function ObservateurJeu(MessageResultat $messageResultat) {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateJeu() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeObjet() {

	}


	/**
	 * @access public
	 * @return Objet
	 */

	public final  function RechercherObjet() {

	}


	/**
	 * @access public
	 * @return MessageJeu[]
	 */

	public final  function RechercherMessageJeu() {

	}


	/**
	 * @access public
	 * @return MessageResultat[]
	 */

	public final  function RechercherMessageResultat() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherEtreJeuManuel() {

	}


	/**
	 * @access public
	 * @return CalculStatistique
	 */

	public final  function RechercherStatistique() {

	}


}
?>