<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class JeuEnCours_View {

	/**
	 * 
	 * @var JeuEnCours
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var JeuEnCours_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param JeuEnCours $model 
	 * @param JeuEnCours_Controller $controller 
	 * @return void
	 */

	public final  function __construct(JeuEnCours $model, JeuEnCours_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInformations() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStrategie() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireRecuDeJeu() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherHistorique() {

	}


	/**
	 * avec filtre joueur
	 * @access public
	 * @return html
	 */

	public final  function AfficherJeuxEnCours() {

	}


}
?>