<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class JeuEnCours_Controller {

	/**
	 * 
	 * @var JeuEnCours
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param JeuEnCours $model 
	 * @return void
	 */

	public final  function __construct(JeuEnCours $model) {

	}


	/**
	 * @access public
	 * @param bool $avoirRecu 
	 * @return void
	 */

	public final  function EnregistrerRecu($avoirRecu) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerJeuEnCours($listeDonnee) {

	}


	/**
	 * @access public
	 * @param MessageResultat[] $messageResultat 
	 * @return void
	 */

	public final  function EnregistrerMessageResultat(MessageResultat[] $messageResultat) {

	}


	/**
	 * @access public
	 * @param MessageJeu[] $messageJeu 
	 * @return void
	 */

	public final  function EnregistrerMessageJeu(MessageJeu[] $messageJeu) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function CompleterCalculStatistique() {

	}


	/**
	 * @access public
	 * @return JeuEnCours[]
	 */

	public final  function RechercherLesJeuxEnCours() {

	}


	/**
	 * @access public
	 * @return JeuEnCours[]
	 */

	public final  function RechercherHistorique() {

	}


	/**
	 * @access public
	 * @param CalculStatistique $nouvelleStatistique 
	 * @return void
	 */

	public final  function EnregistrerStatistique(CalculStatistique $nouvelleStatistique) {

	}


}
?>