<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class LienSite_View {

	/**
	 * 
	 * @var LienSite
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var LienSite_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param LienSite $model 
	 * @param LienSite_Controller $controller 
	 * @return void
	 */

	public final  function __construct(LienSite $model, LienSite_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherLien() {

	}


	/**
	 * éditer ou créer
	 * @access public
	 * @return html
	 */

	public final  function FormulaireLien() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherBoutonSupprimerLien() {

	}


}
?>