<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class MC_Conditions {


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public abstract  function CalculerCondition() ;

	/**
	 * @access public
	 * @return string
	 */

	public abstract  function RenvoyerDescription() ;

}
?>