<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MC_ConditionValeur {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $titre;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;

	/**
	 * Comparée / Testée
	 * @var string
	 * @access private
	 */
	private  $etat;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $type;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $valeur;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $objetAccesseur;


	/**
	 * @access public
	 * @param string $conditionTexte 
	 * @return void
	 */

	public final  function __construct($conditionTexte = "") {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherDescription() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherType() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherEtat() {

	}


	/**
	 * @access public
	 * @return var
	 */

	public final  function RechercherValeur() {

	}


	/**
	 * @access public
	 * @param var $nouvelleValeur 
	 * @return void
	 */

	public final  function ModifierValeur(var $nouvelleValeur) {

	}


	/**
	 * @access public
	 * @param string $nouvelObjetAccesseur Objet.accesseur
	 * @return void
	 */

	public final  function ModifierObjetAccesseur($nouvelObjetAccesseur) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return string
	 */

	public final  function VerifierFormulaireValeur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireValeur() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerValeur($listeDonnee) {

	}


}
?>