<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Messages
 */
require_once('Messages.class.php');

class MessageDemande extends Messages {

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $demandeString;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $periode;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $numero;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nombreNumero;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $grille;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $mise;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $multiplicateur;


	/**
	 * Voir document Objet Message « Demande de jeu » : Messages P39
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ComposerDemande() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerParametreMessage() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireParametreMessage() {

	}


}
?>