<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Messages
 */
require_once('Messages.class.php');

class MessageCondition extends Messages {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var Strategie
	 * @access private
	 */
	private  $strategie;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiantJoueur;

	/**
	 * - Position traitement
- Arborescence au format texte
- Traitement (objet.methode)
- Resultat = false
	 * @var array
	 * @access private
	 */
	private  $tableauCondition;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $resultatFinal = "";


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * 1.2, 1.1, 1 selon le résultat
	 * @access public
	 * @return string
	 */

	public final  function testerTableauCondition() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function lineariserMessageCondition() {

	}


	/**
	 * @access public
	 * @param string $msgConditionLinearise 
	 * @return void
	 */

	public final  function delineariserMessageCondition($msgConditionLinearise) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerMessageLineaire() {

	}


	/**
	 * @access public
	 * @param string $messageCondition 
	 * @return void
	 */

	public final  function ChargerMessageLineaire($messageCondition) {

	}


	/**
	 * Charger une base de travail
Gérer les traitements
Position
Editeur de Conditions
Arborescence
Traitement
	 * @access public
	 * @return html
	 */

	public final  function EditeurConditionTraitement() {

	}


}
?>