<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MouvementComptable_View {

	/**
	 * 
	 * @var MouvementComptable
	 * @access public
	 */
	public  $model;

	/**
	 * 
	 * @var MouvementComptable_Controller
	 * @access public
	 */
	public  $controller;


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireMouvementComptable() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function InterfaceRechercheMouvement() {

	}


	/**
	 * @access public
	 * @param MouvementComptable $model 
	 * @param MouvementComptable_Controller $controller 
	 * @return void
	 */

	public final  function __construct(MouvementComptable $model, MouvementComptable_Controller $controller) {

	}


}
?>