<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MouvementComptable {

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateMouvement;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $montant;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $devise;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $emetteur;

	/**
	 * Type (Couverture, Entreprise, Porte-feuille)
Montant
	 * @var array
	 * @access private
	 */
	private  $tblDestinataire;

	/**
	 * 
	 * @var 
	 * @access private
	 */
	private  $valide;


	/**
	 * @access public
	 * @param  $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function rechercherDate() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function rechercherEmetter() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function rechercherDestinataire() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function rechercherDevise() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function rechercherMouvementValide() {

	}


}
?>