<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MouvementComptable_Controller {

	/**
	 * 
	 * @var MouvementComptable
	 * @access public
	 */
	public  $model;


	/**
	 * @access public
	 * @param MouvementComptable $model 
	 * @return void
	 */

	public final  function __construct(MouvementComptable $model) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function CreerMouvementComptable() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ValiderMouvementComptable() {

	}


	/**
	 * @access public
	 * @param datetime $debutPeriode 
	 * @param dateTime $finPeriode 
	 * @return float
	 */

	public final  function CalculerRentreTotal(datetime $debutPeriode, dateTime $finPeriode) {

	}


	/**
	 * @access public
	 * @param datetime $debutPeriode 
	 * @param dateTime $finPeriode 
	 * @return float
	 */

	public final  function CalculerDebitTotal(datetime $debutPeriode, dateTime $finPeriode) {

	}


	/**
	 * @access public
	 * @param datetime $debutPeriode 
	 * @param datetime $finPeriode 
	 * @return float
	 */

	public final  function CalculerBenefice(datetime $debutPeriode, datetime $finPeriode) {

	}


}
?>