<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Not_ConditionNotification {

	/**
	 * 
	 * @var VariableNotification[]
	 * @access private
	 */
	private  $listeVariable;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nomObjet;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nomMethodeAccesseur;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $valeurComparaison;

	/**
	 * 
	 * @var html
	 * @access private
	 */
	private  $message;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $autorisationNotification;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $avertissement;

	/**
	 * sous la forme objet.methodeRerout ou URL ou NULL
	 * @var string
	 * @access private
	 */
	private  $retourNotification;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return VariableNotification[]
	 */

	public final  function RechercherListeVariable() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherNomObjet() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherNomAccesseur() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherAutorisationNotification() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherRetourNotification() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function RechercherMessage() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherAvertissement() {

	}


	/**
	 * @access public
	 * @param Not_VariableNotification $nouvelleVariable 
	 * @return void
	 */

	public final  function AjouterVariableListe(Not_VariableNotification $nouvelleVariable) {

	}


	/**
	 * @access public
	 * @param string $nouvelleValeur 
	 * @return void
	 */

	public final  function AjouterValeurComparaison($nouvelleValeur) {

	}


	/**
	 * @access public
	 * @param bool $autorisation 
	 * @return void
	 */

	public final  function ChangerAutorisationNotification($autorisation) {

	}


	/**
	 * @access public
	 * @param string $nouvelAvertissement 
	 * @return void
	 */

	public final  function ChangerAvertissement($nouvelAvertissement) {

	}


	/**
	 * @access public
	 * @param Not_VariableNotification $variable 
	 * @return void
	 */

	public final  function SupprimerVariableListe(Not_VariableNotification $variable) {

	}


	/**
	 * @access public
	 * @param string $valeur 
	 * @return void
	 */

	public final  function SupprimerValeurComparaison($valeur) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function ComposerMessageRetour() {

	}


	/**
	 * Null, URL, objet.methode
	 * @access public
	 * @return void
	 */

	public final  function GenererRetourNotification() {

	}


}
?>