<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class NotC_RetourNotification {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var Utilisateur
	 * @access private
	 */
	private  $utilisateur;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $lienRetour;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateLimiteRetour;

	/**
	 * Null, URL, objet.methode
	 * @var string
	 * @access private
	 */
	private  $codeRetour;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Utilisateur
	 */

	public final  function RechercherUtilisateur() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherLienRetour() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateLimite() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherCodeRetour() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function GenererCodeRetour() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function GenererDateRetourLimite() {

	}


	/**
	 * objet.methode, URL, NULL
	 * @access public
	 * @return string
	 */

	public final  function ExecuterRetourNotification() {

	}


}
?>