<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class NotC_VariableNotification {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * int, str, float, bool...
	 * @var string
	 * @access private
	 */
	private  $type;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nomClasse;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $accesseurAttribut;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $variableNotificationType;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherIdentifiant() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherType() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherNomClasse() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherNomAccesseur() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ConstruireVariableType() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function EditeurVariableNotification() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerVariableNotification() {

	}


}
?>