<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Notification {

	/**
	 * 
	 * @var Utilisateur
	 * @access private
	 */
	private  $utilisateur;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateNotification;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $autorisationNotification;

	/**
	 * 
	 * @var ConditionTraitement
	 * @access private
	 */
	private  $conditionTraitement;

	/**
	 * 
	 * @var RetourNotification
	 * @access private
	 */
	private  $retourNotification;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Utilisateur
	 */

	public final  function RechercherUtilisateur() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherAutorisation() {

	}


	/**
	 * @access public
	 * @return ConditionNotification
	 */

	public final  function RechercherConditionNotification() {

	}


	/**
	 * @access public
	 * @return RetourNotification
	 */

	public final  function RechercherRetourNotification() {

	}


	/**
	 * @access public
	 * @param Utilisateur $nouvelUtilisateur 
	 * @return void
	 */

	public final  function ChangerUtilisateur(Utilisateur $nouvelUtilisateur) {

	}


	/**
	 * @access public
	 * @param bool $autorisation 
	 * @return void
	 */

	public final  function ChangerAutorisationNotification($autorisation) {

	}


	/**
	 * @access public
	 * @param ConditionNotification $nouvelleCondition 
	 * @return void
	 */

	public final  function ChangerConditionNotification(ConditionNotification $nouvelleCondition) {

	}


	/**
	 * @access public
	 * @param RetourNotification $nouveauRetourNotification 
	 * @return void
	 */

	public final  function ChangerRetourNotification(RetourNotification $nouveauRetourNotification) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireAutorisationNotification() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function EditeurNotification() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnvoyerMessage() {

	}


}
?>