<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_Facturation {

	/**
	 * 
	 * @var float
	 * @access public
	 */
	public static  $tauxTVA;


	/**
	 * @access public
	 * @return void
	 */

	public final  function __construct() {

	}


	/**
	 * @access public
	 * @param float $montantHT 
	 * @return float
	 */

	public final  function CalculTVA($montantHT) {

	}


}
?>