<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_GestionnaireDate {


	/**
	 * @access public
	 * @return void
	 */

	public final  function __construct() {

	}


	/**
	 * @access public
	 * @param datetime $dateDebut 
	 * @param int $nombreTirage 
	 * @return datetime
	 */

	public final  function AdditionnerDateEtNbrTirage(datetime $dateDebut, $nombreTirage) {

	}


	/**
	 * @access public
	 * @param datetime $dateTirage 
	 * @return int
	 */

	public final  function RenvoyerNumeroTirage(datetime $dateTirage) {

	}


	/**
	 * @access public
	 * @param int $numeroTirage 
	 * @return datetime
	 */

	public final  function RenvoyerDateTirage($numeroTirage) {

	}


	/**
	 * @access public
	 * @param int $numeroTirage 
	 * @return int
	 */

	public final  function RenvoyerAnneeTirage($numeroTirage) {

	}


	/**
	 * @access public
	 * @param int $numeroTirage 
	 * @return int
	 */

	public final  function RenvoyerMoisTirage($numeroTirage) {

	}


	/**
	 * @access public
	 * @param int $numeroTirage 
	 * @return int
	 */

	public final  function RenvoyerJourTirage($numeroTirage) {

	}


	/**
	 * @access public
	 * @param int $numeroTirage 
	 * @return string
	 */

	public final  function RenvoyerHeureTirage($numeroTirage) {

	}


	/**
	 * @access public
	 * @param datetime $date 
	 * @return string
	 */

	public final  function EcrireDate(datetime $date) {

	}


}
?>