<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_ConvertisseurMonetique {


	/**
	 * @access public
	 * @return void
	 */

	public final  function __construct() {

	}


	/**
	 * @access public
	 * @param float $sommeEuro 
	 * @return int
	 */

	public final  function ConvertirEuroVersCredit($sommeEuro) {

	}


	/**
	 * @access public
	 * @param int $sommeCredit 
	 * @return float
	 */

	public final  function ConvertirCreditVersEuro($sommeCredit) {

	}


}
?>