<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_IdentificationUtilisateur {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $idUtilisateur;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $typeAbonnement;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $droit;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateConnexion;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $adresseIP;


	/**
	 * @access public
	 * @param int $identifiantUtilisateur 
	 * @param string $typeAbonnement 
	 * @param string $droit 
	 * @return void
	 */

	public final  function __construct($identifiantUtilisateur, $typeAbonnement, $droit) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireConnexion() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function VerificationConnexion() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function CreationSession() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DestructionSession() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherBoutonDeconnexion() {

	}


}
?>