<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Portefeuille_Controller {

	/**
	 * 
	 * @var Portefeuille
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Portefeuille $model 
	 * @return void
	 */

	public final  function __construct(Portefeuille $model) {

	}


	/**
	 * @access public
	 * @param int $somme 
	 * @return void
	 */

	public final  function ChangerCredit($somme) {

	}


	/**
	 * @access public
	 * @param Facturew $facture 
	 * @return void
	 */

	public final  function AjouterFacture(Facturew $facture) {

	}


	/**
	 * @access public
	 * @param Versement $versement 
	 * @return void
	 */

	public final  function AjouterVersement(Versement $versement) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerModel() {

	}


}
?>