<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ResultatTeam_View {

	/**
	 * 
	 * @var ResultatTeam
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var ResultatTeam_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param ResultatTeam $model 
	 * @param ResultatTeam_Controller $controller 
	 * @return void
	 */

	public final  function __construct(ResultatTeam $model, ResultatTeam_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStatistiqueDernierJeu() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStatistiqueTousJeux() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStatistiqueMembre() {

	}


}
?>