<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ResultatTeam {

	/**
	 * 
	 * @var Team
	 * @access private
	 */
	private  $team;

	/**
	 * Date de jeu  [ Utilisateur [Technique, Somme finale, Somme totale, Objet statistique pour la période début_utilisation jusqu'au dernier tirage] ]
	 * @var array()
	 * @access private
	 */
	private  $tableauStatistique;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Team
	 */

	public final  function RechercherTeam() {

	}


	/**
	 * @access public
	 * @param string $type "" = Tous les membres derniers jeu
"membre" = Tous les membre tous les jeux
"joueur" = Joueur tous les jeux
	 * @param int $idJoueur 
	 * @return array
	 */

	public final  function CalculerStatistique($type = "", $idJoueur = 0) {

	}


}
?>