<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Simulateur_View {

	/**
	 * 
	 * @var Simulateur
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Simulateur_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Simulateur $model 
	 * @param Facture_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Simulateur $model, Facture_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStrategieJoueur() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireSimulationManuelle() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherComparatifStratégieEtTechnique() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function FormulaireSimulationGlobale() {

	}


}
?>