<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Simulateur {

	/**
	 * 
	 * @var Strategie[]
	 * @access private
	 */
	private  $listeStrategie;

	/**
	 * 
	 * @var Joueur
	 * @access private
	 */
	private  $joueur;

	/**
	 * 
	 * @var JeuEnCours[]
	 * @access private
	 */
	private  $jeuEnCours;

	/**
	 * 
	 * @var JeuEnSimulation[]
	 * @access private
	 */
	private  $jeuEnSimulation;

	/**
	 * 
	 * @var MessageJeu[]
	 * @access private
	 */
	private  $messageJeu;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EcouteStrategie() {

	}


	/**
	 * @access public
	 */

	public final  function RechercherUtilisateur() {

	}


	/**
	 * @access public
	 * @return JeuEnCours[]
	 */

	public final  function RechercherJeuEnCours() {

	}


	/**
	 * @access public
	 * @return JeuEnSimulation[]
	 */

	public final  function RechercherJeuEnSimulation() {

	}


}
?>