<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategieUtilisateur {

	/**
	 * 
	 * @var Utilisateur
	 * @access private
	 */
	private  $utilisateurProprietaire;

	/**
	 * 
	 * @var Utilisateur
	 * @access private
	 */
	private  $utilisateur;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $favoris;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $partage;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreUtilisation;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $tarifLocation;

	/**
	 * 
	 * @var Strategie
	 * @access private
	 */
	private  $strategie;

	/**
	 * 
	 * @var int
	 * @access public
	 */
	public  $tarifVente;


	/**
	 * @access public
	 * @return Strategie
	 */

	public final  function RechercherStrategie() {

	}


	/**
	 * @access public
	 * @return Utilisateur
	 */

	public final  function RechercherProprietaire() {

	}


	/**
	 * @access public
	 * @return Utilisateur
	 */

	public final  function RechercherUtilisateur() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherFavoris() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercheInfoPartage() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherTarifLocation() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherTarifVente() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNombreUtilisation() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function CalculerTarifVente() {

	}


}
?>