<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategieConditionGestion {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private static  $titre;

	/**
	 * 
	 * @var StrategieEntete
	 * @access private
	 */
	private  $entete;

	/**
	 * 
	 * @var Conditions[]
	 * @access private
	 */
	private  $listeConditionSuspension;

	/**
	 * 
	 * @var Conditions[]
	 * @access private
	 */
	private  $listeConditionReprise;

	/**
	 * 
	 * @var Conditions[]
	 * @access private
	 */
	private  $listeConditionArreter;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param string $action Suspendre, Reprendre, Arrêter
	 * @return Conditions[]
	 */

	public final  function RechercherConditions($action) {

	}


	/**
	 * @access public
	 * @param Conditions $condition 
	 * @param string $liste Suspendre, Reprendre, Arreter
	 * @return void
	 */

	public final  function AjouterConditions(Conditions $condition, $liste) {

	}


	/**
	 * @access public
	 * @param Conditions $condition 
	 * @param string $liste Suspendre, Reprendre, Arreter
	 * @return void
	 */

	public final  function SupprimerConditions(Conditions $condition, $liste) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerListes() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function EcrireTexteDescription() {

	}


}
?>