<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Strategie_Controller {

	/**
	 * 
	 * @var Strategie
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Strategie $model 
	 * @return void
	 */

	public final  function __construct(Strategie $model) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function ChangerEntete($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function ChangerPeriode0($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return array
	 */

	public final  function ChangerPeriodeN($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function ChangerConditionGestion($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return MessageDemande
	 */

	public final  function GenererMessageDemande($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return MessageJeu
	 */

	public final  function GenererMessageJeu($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function DemarrerDemandeManuelle($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Strategie
	 */

	public final  function CreerStrategie() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function ChangerInfoStrategie($listeDonnee) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ReinitialiserStrategie() {

	}


	/**
	 * @access public
	 * @return PartieEnCours[]
	 */

	public final  function RechercherPartieEnCours() {

	}


	/**
	 * @access public
	 * @return PartieEnSimulation[]
	 */

	public final  function RechercherPartieEnSimulation() {

	}


}
?>