<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategieEntete {

	/**
	 * 
	 * @var Strategie
	 * @access private
	 */
	private  $strategie;

	/**
	 * 
	 * @var TechniqueComposee[]
	 * @access private
	 */
	private  $listeTechnique;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $periodeJeu;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombrePartieJouee;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombrePartiePassee;

	/**
	 * 
	 * @var CalculStatistique
	 * @access private
	 */
	private  $dernierMessageResultat;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $suspendu;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $arretee;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $confirmee;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Strategie
	 */

	public final  function RechercherStrategie() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateDebut() {

	}


	/**
	 * @access public
	 * @return TechniqueComposee[]
	 */

	public final  function RechercherListeTechnique() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherPartieJouee() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherPartiePassee() {

	}


	/**
	 * Confirmée, Arrêtée ou Suspendue
	 * @access public
	 * @return string
	 */

	public final  function RechercherEtatStrategie() {

	}


	/**
	 * @access public
	 * @param TechniqueComposee $technique 
	 * @return void
	 */

	public final  function AjouterTechnique(TechniqueComposee $technique) {

	}


	/**
	 * @access public
	 * @param TechniqueComposee $technique 
	 * @param TechniqueComposee $nouvelleValeur 
	 * @return void
	 */

	public final  function ModifierTechnique(TechniqueComposee $technique, TechniqueComposee $nouvelleValeur) {

	}


	/**
	 * @access public
	 * @param TechniqueComposee $technique 
	 * @return void
	 */

	public final  function SupprimerTechnique(TechniqueComposee $technique) {

	}


	/**
	 * @access public
	 * @param datetime $nouvelleDate 
	 * @return void
	 */

	public final  function ChangerDateDebut(datetime $nouvelleDate) {

	}


	/**
	 * @access public
	 * @param int $nouvellePeriode 
	 * @return void
	 */

	public final  function ChangerPeriodeJeu($nouvellePeriode) {

	}


	/**
	 * @access public
	 * @param string $nouvelEtat Suspendue, Arrêtée, Confirmée
	 * @return void
	 */

	public final  function ChangerEtat($nouvelEtat) {

	}


	/**
	 * @access public
	 * @param MessageResultat $resultat 
	 * @return void
	 */

	public final  function ChangerDernierResultat(MessageResultat $resultat) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function IncrementerPartieJouee() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function IncrementerPartieJouee() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function AfficheTexteDescription() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerEntete() {

	}


}
?>