<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategieUtilisateur_Controller {

	/**
	 * 
	 * @var StrategieUtilisateur
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param StrategieUtilisateur $model 
	 * @return void
	 */

	public final  function __construct(StrategieUtilisateur $model) {

	}


	/**
	 * @access public
	 * @param int $idStrategie 
	 * @return void
	 */

	public final  function EnregistrerFavoris($idStrategie) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function CreerStrategieUtilisateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerConfigPartage($listeDonnee) {

	}


	/**
	 * @access public
	 * @param int $valeur 
	 * @return void
	 */

	public final  function EnregistrerTarifLocation($valeur) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerTarifVente() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerNouvelleStrategieUtilisateur() {

	}


}
?>