<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategiePeriodeN {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private static  $titre;

	/**
	 * 
	 * @var StrategieEntete
	 * @access private
	 */
	private  $entete;

	/**
	 * 
	 * @var StrategieResultatPeriodeN
	 * @access public
	 */
	public  $resultatPeriodeN;

	/**
	 * 
	 * @var StrategieTraitementPeriodeN
	 * @access public
	 */
	public  $traitementPeriodeN;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param StrategieResultatPeriodeN $resultat 
	 * @return void
	 */

	public final  function EnregistrerResultatPeriodeN(StrategieResultatPeriodeN $resultat) {

	}


	/**
	 * @access public
	 * @param StrategieTraitementPeriodeN $traitement 
	 * @return void
	 */

	public final  function EnregistrerTraitementPeriodeN(StrategieTraitementPeriodeN $traitement) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerPeriodeN() {

	}


	/**
	 * @access public
	 * @return StrategieResultatPeriodeN
	 */

	public final  function RechercherResultatPeriodeN() {

	}


	/**
	 * @access public
	 * @return StrategieTraitementPeriodeN
	 */

	public final  function RechercherTraitementPeriodeN() {

	}


}
?>