<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Strategie {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $titre;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $version;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $niveau;

	/**
	 * 
	 * @var StrategieEntete
	 * @access private
	 */
	private  $enteteStrategie;

	/**
	 * 
	 * @var StrategiePeriode0
	 * @access private
	 */
	private  $periode0;

	/**
	 * 
	 * @var StrategiePeriodeN
	 * @access private
	 */
	private  $listePeriode;

	/**
	 * 
	 * @var StrategieConditionGestion
	 * @access private
	 */
	private  $conditionGestionStrategie;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return EnteteStrategie
	 */

	public final  function RechercherEntete() {

	}


	/**
	 * @access public
	 * @return StrategiePeriode0
	 */

	public final  function RechercherPeriode0() {

	}


	/**
	 * @access public
	 * @return StrategiePeriodeN
	 */

	public final  function RechercherPeriodeN() {

	}


	/**
	 * @access public
	 * @return ConditionGestionStrategie
	 */

	public final  function RechercherConditionGestion() {

	}


	/**
	 * @access public
	 * @return CalculStatistique
	 */

	public final  function CalculStatistique() {

	}


	/**
	 * Nombre d'utilisateur, nombre d'utilisation
Liste d'utilisateur / utilisation
	 * @access public
	 * @return array
	 */

	public final  function RechercherUtilisateurStrategie() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInfoStrategie() {

	}


}
?>