<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TableauDesGains_Controller {

	/**
	 * 
	 * @var TableauDesGains
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param TableauDesGains $model 
	 * @return void
	 */

	public final  function __construct(TableauDesGains $model) {

	}


	/**
	 * @access public
	 * @param int $quantiteNumero 
	 * @param int $mise 
	 * @return void
	 */

	public final  function EnregistrerTableauDesGains($quantiteNumero, $mise) {

	}


}
?>