<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TCConditionNumero_Controller {

	/**
	 * 
	 * @var TCConditionNumero
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param TCConditionNumero $model 
	 * @return void
	 */

	public final  function __construct(TCConditionNumero $model) {

	}


	/**
	 * @access public
	 * @param int[] $listeNumero 
	 * @return void
	 */

	public final  function ConstruireListeNumero(int[] $listeNumero) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ConstruireTexteDescription() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ComposerListeNumeroFormatee() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public abstract  function CalculerNumero() ;

	/**
	 * @access public
	 * @return TCConditionNumero[]
	 */

	public final  function RechercherConditionsNumero() {

	}


}
?>