<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class TCConditionGrille {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $grilleJeuFormatee;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreGrille;

	/**
	 * variable / fixe
	 * @var string
	 * @access private
	 */
	private  $typeGrille;

	/**
	 * valeur initial, [valeur ou coefficient]
	 * @var array
	 * @access private
	 */
	private  $valeurGrille;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $texteDescription;


	/**
	 * @access public
	 * @param string $messageJeu 
	 * @return void
	 */

	public abstract  function __construct($messageJeu) ;

	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNombreGrille() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTexteDescription() {

	}


}
?>