<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class TCConditionNumero {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreTirage;

	/**
	 * 
	 * @var int[]
	 * @access private
	 */
	private  $listeNumero;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $listeNumeroFormatee;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $texteDescription;


	/**
	 * @access public
	 * @param string $messageDemande 
	 * @return void
	 */

	public final  function __construct($messageDemande) {

	}


	/**
	 * @access public
	 * @return int[]
	 */

	public final  function RechercherListeNumero() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherListeNumeroFormatee() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTexteDescription() {

	}


}
?>