<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TCConditionPeriode_Controller {

	/**
	 * 
	 * @var TCConditionPeriode
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param TCConditionPeriode $model 
	 * @return void
	 */

	public final  function __construct(TCConditionPeriode $model) {

	}


	/**
	 * @access public
	 * @return TCConditionPeriode[]
	 */

	public final  function RechercherListeConditionPeriode() {

	}


}
?>