<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class TCConditionMultiplicateur_Controller {

	/**
	 * 
	 * @var TCConditionMultiplicateur
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param MessageDemande $messageDemande 
	 * @return void
	 */

	public final  function __construct(MessageDemande $messageDemande) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ComposerTexteDescription() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DecomposerMessageDemande() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ComposerMessageJeu() {

	}


	/**
	 * @access public
	 * @return TCConditionMultiplicateur[]
	 */

	public final  function RechercherConditionsMultiplicateur() {

	}


}
?>