<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TCConditionMise_Controller {

	/**
	 * 
	 * @var TCConditionMise
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param TCConditionMise $model 
	 * @return void
	 */

	public final  function __construct(TCConditionMise $model) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DecomposerMessageDemande() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ComposerMessageJeu() {

	}


	/**
	 * @access public
	 */

	public final  function ComposerTexteDescription() {

	}


	/**
	 * @access public
	 * @return TCConditionGrille[]
	 */

	public final  function RechercherConditionsGrille() {

	}


}
?>