<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class TCConditionMise {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $conditionMiseFormatee;

	/**
	 * fixe ou variable
	 * @var string
	 * @access private
	 */
	private  $typeMise;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $valeurFixe;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $valeurSupplementaire;


	/**
	 * @access public
	 * @param MessageDemande $messageDemande 
	 * @return void
	 */

	public final  function __construct(MessageDemande $messageDemande) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeMise() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherValeurFixe() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherValeurSupplémentaire() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTexteDescription() {

	}


}
?>