<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Team_View {

	/**
	 * 
	 * @var Team
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var Team_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param Team $model 
	 * @param Team_Controller $controller 
	 * @return void
	 */

	public final  function __construct(Team $model, Team_Controller $controller) {

	}


	/**
	 * Récapitulatif global
	 * @access public
	 * @return html
	 */

	public final  function AfficherAccueilTeam() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherMembre() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherResultat() {

	}


	/**
	 * Technique + Joueur
	 * @access public
	 * @return html
	 */

	public final  function AfficherResultatDetaille() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherObjectifFinancier() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireModifierNom() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireObjectifEquipe() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireObjectifFinancier() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireCommentaire() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireInscription() {

	}


}
?>