<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TechniqueComposee_View {

	/**
	 * 
	 * @var TechniqueComposee
	 * @access private
	 */
	private  $model;

	/**
	 * 
	 * @var TechniqueComposee_Controller
	 * @access private
	 */
	private  $controller;


	/**
	 * @access public
	 * @param TechniqueComposee $model 
	 * @param TechniqueComposee_Controller $controller 
	 * @return void
	 */

	public final  function __construct(TechniqueComposee $model, TechniqueComposee_Controller $controller) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherInfoTechnique() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherStatistiqueTechnique() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function AfficherTableauResultat() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireEditionInformation() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireRecalculerStatistique() {

	}


	/**
	 * @access public
	 */

	public final  function FormulaireCreation() {

	}


}
?>