<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TechniqueComposee_Controller {

	/**
	 * 
	 * @var TechniqueComposee
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param TechniqueComposee $model 
	 * @return void
	 */

	public final  function __construct(TechniqueComposee $model) {

	}


	/**
	 * @access public
	 * @return CalculStatistique
	 */

	public final  function DemandeCalculStatistique() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerTechniqueComposee($listeDonnee) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ModifierVersion() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee db + fichiers
	 * @return void
	 */

	public final  function EnregistrerNouvelleTechnique($listeDonnee) {

	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function CalculerNiveauTechnique() {

	}


	/**
	 * @access public
	 * @return JeuEnSimulation[]
	 */

	public final  function RechercherJeuEnSimulation() {

	}


}
?>