<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Utilisateur {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * Super administrateur, administrateur, utilisateur
	 * @var string
	 * @access private
	 */
	private  $type;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $login;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $motDePasse;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $adresse1;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $adresse2;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $codePostal;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $ville;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $mail;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $devise;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $cagnotteJeuReel;

	/**
	 * 
	 * @var AbonnementUtilisateur
	 * @access private
	 */
	private  $abonnement;

	/**
	 * 
	 * @var Team
	 * @access private
	 */
	private  $team;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */
	public $template;

	public final  function __construct($listeDonnee = false) {
		$this->template = 'tpl/template.php';
		if(!$listeDonnee)
			$login = 'test';
	}

	public final function getLogin()
		{
		return $this->login;
		}
	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInfoUtilisateur() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherCagnotteJeu() {

	}


}
?>