l<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Utilisateur_Controller {

	/**
	 * 
	 * @var Utilisateur
	 * @access private
	 */
	private  $model;


	/**
	 * @access public
	 * @param Utilisateur $model 
	 * @return void
	 */

	public final  function __construct(Utilisateur $model) {

	}


	/**
	 * @access public
	 * @param int $somme positif ou négatif
	 * @return void
	 */

	public final  function ChangerCagnotteJeu($somme) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function Remise0CagnotteJeu() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return bool
	 */

	public final  function TesterInfoFormulaireUtilisateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function ChangerInfoUtilisateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return bool
	 */

	public final  function TesterFormChangerMotdepasse($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouveauMotdepasse($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return bool
	 */

	public final  function TesterFormNouvelUtilisateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerNouvelUtilisateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param string $typeUtilisateur 
	 * @return void
	 */

	public final  function ChangerTypeUtilisateur($typeUtilisateur) {

	}


}
?>