<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class ContenuHTML {

	/**
	 * 
	 * @var EditeurHTML
	 * @access private
	 */
	private  $editeurHTML;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $affichagePublic;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $emplacementOccupe;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $codeHTML;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $actif;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeAffichage() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherCodeHTML() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherEmplacementOccupe() {

	}


}
?>