<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class EditeurHTML {

	/**
	 * 
	 * @var string[]
	 * @access private
	 */
	private  $listeEmplacementOccupe;

	/**
	 * 
	 * @var string[]
	 * @access private
	 */
	private  $listeEmplacementlibre;

	/**
	 * 
	 * @var ContenuHTML[]
	 * @access private
	 */
	private  $listeContenuHTML;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherEditionPublique() {

	}


	/**
	 * @access public
	 * @return string[]
	 */

	public final  function RechercherEmplacementOccupe() {

	}


	/**
	 * @access public
	 * @return string[]
	 */

	public final  function RechercherEmplacementLibre() {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function RechercherContenuPrincipal() {

	}


}
?>