<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Facture {

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $date;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $montantHT;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $numeroFacture;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $moyenPaiement;

	/**
	 * 
	 * @var Abonnement
	 * @access private
	 */
	private  $abonnement;

	/**
	 * 
	 * @var Joueur
	 * @access private
	 */
	private  $joueur;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $creditCommande;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $fichierFacture;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInformationFacture() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherEmplacementFichier() {

	}


}
?>