<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Jeu {

	/**
	 * 
	 * @var array
	 * @access private
	 */
	private  $listeObservateur;

	/**
	 * 
	 * @var MessageJeu[]
	 * @access private
	 */
	private  $listeMessageJeu;

	/**
	 * 
	 * @var array
	 * @access private
	 */
	private  $listeResultat;

	/**
	 * 
	 * @var MessageResultat
	 * @access private
	 */
	private  $messageResultat;

	/**
	 * Numéro de proposition de jeu dans les messages de jeu
Type de jeu
Liste de numéro trouvé
Dépense
Gain
	 * @var array
	 * @access private
	 */
	private  $modeleResultat;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $GainFinal;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $DepenseFinale;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * Déclancher la méthode CalculerJeuxRéels
	 * @access public
	 * @param array $listeResultat 
	 * @return void
	 */

	public final  function ObservateurTirage($listeResultat) {

	}


	/**
	 * @access public
	 * @param array $listeResultat 
	 * @return void
	 */

	public final  function CalculerJeuxReels($listeResultat) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherObservateur() {

	}


	/**
	 * @access public
	 * @return MessageJeu[]
	 */

	public final  function RechercherListeMessageJeu() {

	}


	/**
	 * @access public
	 * @param MessageJeu $messageJeu 
	 * @param int $numTirage 
	 * @return void
	 */

	public final  function DemarrerTraitementSimulation(MessageJeu $messageJeu, $numTirage) {

	}


	/**
	 * @access public
	 * @return MessageResultat
	 */

	public final  function RechercherMessageResultat() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherListeResultat() {

	}


}
?>