<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class LienSite {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * interne ou externe
	 * @var string
	 * @access private
	 */
	private  $typeLien;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $url;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $texte = "";

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeLien() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherUrl() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTexte() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherDescription() {

	}


}
?>