<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MC_ConditionVariable {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiantJoueur;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $titreObjet;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $titreAccesseur;

	/**
	 * int, Objet, datetime ...
	 * @var string
	 * @access private
	 */
	private  $typeValeur;

	/**
	 * 
	 * @var var
	 * @access private
	 */
	private  $valeur;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;


	/**
	 * @access public
	 * @param string $objetAccesseur Objet.Accesseur
	 * @return void
	 */

	public final  function __construct($objetAccesseur = "") {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherDescription() {

	}


	/**
	 * @access public
	 * @return Objet
	 */

	public final  function RechercherObjet() {

	}


	/**
	 * @access public
	 * @return var
	 */

	public final  function RechercherValeur() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherClasse() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeValeur() {

	}


	/**
	 * @access public
	 * @param string $nouelObjetAccesseur 
	 * @return void
	 */

	public final  function ModifierObjetAccesseur($nouelObjetAccesseur) {

	}


	/**
	 * @access public
	 * @param int $identifiantJoueur 
	 * @return void
	 */

	public final  function ModifierJoueur($identifiantJoueur) {

	}


	/**
	 * @access public
	 * @param var $filtreValeur 
	 * @return array
	 */

	public final  function ListerClasseAccesseur(var $filtreValeur = false) {

	}


	/**
	 * @access public
	 * @return html
	 */

	public final  function FormulaireVariable() {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return string
	 */

	public final  function VerifierFormulaireVariable($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function EnregistrerFormulaire($listeDonnee) {

	}


}
?>