<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class Messages {

	/**
	 * 
	 * @var Objet
	 * @access private
	 */
	private  $objetEmetteur;

	/**
	 * 
	 * @var Objet[]
	 * @access private
	 */
	private  $listeRecepteur;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $idMessagePrecedent;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Objet
	 */

	public final  function RechercherEmetteur() {

	}


	/**
	 * @access public
	 * @return Objet[]
	 */

	public final  function RechercherListeRecepteur() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherMessagePrecedent() {

	}


	/**
	 * @access public
	 * @param Objet $nouveauRecepteur 
	 * @return void
	 */

	public final  function AjouterRecepteur(Objet $nouveauRecepteur) {

	}


	/**
	 * @access public
	 * @param Objet $recepteur 
	 * @return void
	 */

	public final  function SupprimerRecepteur(Objet $recepteur) {

	}


}
?>