<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Messages
 */
require_once('Messages.class.php');

class MessageJeu extends Messages {

	/**
	 * 
	 * @var MJ_PropositionJeu[]
	 * @access private
	 */
	private  $listePropositionJeu;

	/**
	 * 
	 * @var MessageDemande
	 * @access private
	 */
	private  $messageDemande;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * @access public
	 * @param string $messageJeu 
	 * @return void
	 */

	public final  function Hydrateur($messageJeu) {
	//ERROR: METHOD CAN'T BE OVERLOADED, PARENT HAS DECLARED IT 'final'!
	}


	/**
	 * @access public
	 * @param string $messageJeu 
	 * @return void
	 */

	public final  function ChangerMessageDemande($messageJeu) {

	}


	/**
	 * @access public
	 * @param string $messageJeu 
	 * @return void
	 */

	public final  function ExtraireInfoMessageJeu($messageJeu) {

	}


	/**
	 * @access public
	 * @return MJ_PropositionJeu[]
	 */

	public final  function ComposerListePropositionJeu() {

	}


	/**
	 * @access public
	 * @param MJ_PropositionJeu $propositionJeu 
	 * @return void
	 */

	public final  function AjouterPropositionJeu(MJ_PropositionJeu $propositionJeu) {

	}


	/**
	 * @access public
	 * @param MJ_PropositionJeu $propositionJeu 
	 * @return void
	 */

	public final  function SupprimerPropositionJeu(MJ_PropositionJeu $propositionJeu) {

	}


}
?>