<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class MJ_PropositionJeu {

	/**
	 * 
	 * @var MessageJeu
	 * @access private
	 */
	private  $messageJeu;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $listeNumero;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $mise;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nombreGrille;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $multiplicateur;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ExtraireInfoMessageJeu() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateTirage() {

	}


	/**
	 * @access public
	 * @return int[]
	 */

	public final  function RechercherListeNumero() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherMise() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherGrille() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeMultiplicateur() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherValeurMultiplicateur() {

	}


}
?>