<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_NiveauTechnique {

	/**
	 * stratégie ou technique composée
	 * @var string
	 * @access private
	 */
	private  $typeObjet;

	/**
	 * En cours ou simulée
	 * @var string
	 * @access private
	 */
	private  $typeJeu;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiantObjet;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateFin;

	/**
	 * 
	 * @var MessageStatistique
	 * @access private
	 */
	private  $statistique;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @param string $nouveauType 
	 * @return void
	 */

	public final  function ChangerTypeObjet($nouveauType) {

	}


	/**
	 * @access public
	 * @param string $nouveauType 
	 * @return void
	 */

	public final  function ChangerTypeJeu($nouveauType) {

	}


	/**
	 * @access public
	 * @param int $identifiantObjet 
	 * @return void
	 */

	public final  function ChangerObjet($identifiantObjet) {

	}


	/**
	 * @access public
	 * @param datetype $nouvelleDate 
	 * @return void
	 */

	public final  function ChangerDateDebut(datetype $nouvelleDate) {

	}


	/**
	 * @access public
	 * @param datetime $nouvelleDate 
	 * @return void
	 */

	public final  function ChangerDateFin(datetime $nouvelleDate) {

	}


	/**
	 * note d'amélioration de jeu : Stat(coef d'amelioration)
Note amélioration bénéfince Stat(coef gain)
	 * @access public
	 * @return array
	 */

	public final  function CalculerNotes() {

	}


	/**
	 * les deux notes
	 * @access public
	 * @return array
	 */

	public final  function ComposerCodeRetour() {

	}


}
?>