<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_Linerisation {


	/**
	 * @access public
	 * @return void
	 */

	public final  function __construct() {

	}


	/**
	 * @access public
	 * @param Objet $objetDeTravail 
	 * @return string
	 */

	public final  function String(Objet $objetDeTravail) {

	}


	/**
	 * @access public
	 * @param string $objetLinearise 
	 * @return Objet
	 */

	public final  function Objet($objetLinearise) {

	}


}
?>