<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Outil_GestionnairePDF {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $codeHtml;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $emplacementFichier;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nomFichier;


	/**
	 * @access public
	 * @param string $emplacementFichier répertoire + fichier
	 * @return void
	 */

	public final  function __construct($emplacementFichier = "") {

	}


	/**
	 * @access public
	 * @param string $nouveauCode 
	 * @return void
	 */

	public final  function changerCodeHTML($nouveauCode) {

	}


	/**
	 * @access public
	 * @param string $nouvelEmplacement 
	 * @return void
	 */

	public final  function changerEmplacementFichier($nouvelEmplacement) {

	}


	/**
	 * @access public
	 * @param string $nouveauNom 
	 * @return void
	 */

	public final  function changerNomFichier($nouveauNom) {

	}


	/**
	 * Renvoi le chemin d'accès du fichier
	 * @access public
	 * @return string
	 */

	public final  function EnregistrerFichierPdf() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherUrlFichierPdf() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function SupprimerPdf() {

	}


}
?>