<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Portefeuille {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var Abonnement
	 * @access private
	 */
	private  $abonnement;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $credit;

	/**
	 * 
	 * @var array
	 * @access private
	 */
	private  $listeFacture;

	/**
	 * 
	 * @var array
	 * @access private
	 */
	private  $listeVersement;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Abonnement
	 */

	public final  function rechercherAbonnement() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function rechercherCredit() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function rechercherListeFacture() {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function rechercherListeVersement() {

	}


}
?>