<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StatistiquePartie {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $numeroPartie;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $gainGlobalEuro;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $gainGlobalCredit;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $DepenseGlobaleEuro;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $DepenseGlobaleCredit;

	/**
	 * 
	 * @var SP_GainUtilisateur[]
	 * @access private
	 */
	private  $tableauUtilisateur;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreParticipantPartie;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNumeroPartie() {

	}


	/**
	 * @access public
	 * @return float
	 */

	public final  function RechercherGainGlobalEuro() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherGainGlobalCredit() {

	}


	/**
	 * @access public
	 * @return SP_GainUtilisateur[]
	 */

	public final  function RechercherTableauParticipant() {

	}


	/**
	 * @access public
	 */

	public final  function RechercherNombreParticipant() {

	}


	/**
	 * @access public
	 * @param float $nouvelleSomme 
	 * @return void
	 */

	public final  function ModifierGainGlobalEuro($nouvelleSomme) {

	}


	/**
	 * @access public
	 * @param int $nouvelleSomme 
	 * @return void
	 */

	public final  function ModifierGainGlobalCredit($nouvelleSomme) {

	}


	/**
	 * @access public
	 * @param float $nouvelleSomme 
	 * @return void
	 */

	public final  function ModifierDepenseGlobaleEuro($nouvelleSomme) {

	}


	/**
	 * @access public
	 * @param int $nouvelleSomme 
	 * @return void
	 */

	public final  function ModifierDepenseGlobaleCredit($nouvelleSomme) {

	}


	/**
	 * @access public
	 * @param SP_GainUtilisateur $nouvelUtilisateur 
	 * @return void
	 */

	public final  function AjouterUtilisateurTableau(SP_GainUtilisateur $nouvelUtilisateur) {

	}


	/**
	 * @access public
	 * @param SP_GainUtilisateur $utilisateur 
	 * @return void
	 */

	public final  function SupprimerUtilisateurTableau(SP_GainUtilisateur $utilisateur) {

	}


	/**
	 * @access public
	 * @param int $nouveauNombre 
	 * @return void
	 */

	public final  function ModifierNombreParticipant($nouveauNombre) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function RemplirTableauParticipant() {

	}


	/**
	 * date, valeur, progression
	 * @access public
	 * @return array
	 */

	public final  function RechercherEvolutionGain() {

	}


	/**
	 * date, valeur, progression
	 * @access public
	 * @return array
	 */

	public final  function RechercherEvolutionDepense() {

	}


	/**
	 * Utilisateur + SP_GainUtilisateur
	 * @access public
	 * @return array
	 */

	public final  function RechercherListeVainqueur() {

	}


	/**
	 * Utilisateur + SP_GainUtilisateur
	 * @access public
	 * @return array
	 */

	public final  function RechercherListePerdants() {

	}


	/**
	 * Utilisateur + SP_GainUtilisateur
	 * @access public
	 * @return array
	 */

	public final  function RechercherUtilisateurVendreur() {

	}


	/**
	 * Utilisateur + SP_GainUtilisateur
	 * @access public
	 * @return array
	 */

	public final  function RechercherUtilisateurAcheteurStrategie() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerStatistiquePartie() {

	}


}
?>