<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategiePeriode0 {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private static  $titre;

	/**
	 * 
	 * @var StrategieEntete
	 * @access private
	 */
	private  $entete;

	/**
	 * 
	 * @var Conditions[]
	 * @access private
	 */
	private  $listeConditionStrategique;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Conditions[]
	 */

	public final  function RechercherConditionsStrategique() {

	}


	/**
	 * @access public
	 * @param Conditions $nouvelleCondition 
	 * @return void
	 */

	public final  function AjouterCondition(Conditions $nouvelleCondition) {

	}


	/**
	 * @access public
	 * @param Condtions $condition 
	 * @return void
	 */

	public final  function SupprimerCondition(Condtions $condition) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function EnregistrerConditions() {

	}


	/**
	 * @access public
	 */

	public final  function AfficherTexteDescription() {

	}


}
?>