<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class StrategieTraitementPeriodeN {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private static  $titre;

	/**
	 * 
	 * @var StrategiePeriodeN
	 * @access private
	 */
	private  $periodeN;

	/**
	 * 
	 * @var Conditions[]
	 * @access private
	 */
	private  $listeCondition;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return Conditions[]
	 */

	public final  function RechercherListeConditions() {

	}


	/**
	 * @access public
	 * @param Conditions[] $listeConditions 
	 * @return void
	 */

	public final  function ModifierListeConditions(Conditions[] $listeConditions) {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function AfficherTexteDescription() {

	}


}
?>