<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TableauDesGains {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreJoue;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $mise;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $gain;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $aVie;

	/**
	 * Chance / formulation en texte
	 * @var array
	 * @access private
	 */
	private  $chanceGain;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $depense;


	/**
	 * @access public
	 * @param int $quantiteNumero 
	 * @param int $mise 
	 * @return void
	 */

	public final  function __construct($quantiteNumero, $mise) {

	}


	/**
	 * Retourner tableau de gain
	 * @access public
	 * @param  $nombreJ 
	 * @return int
	 */

	public final  function RenvoyerGain($nombreJ) {

	}


	/**
	 * @access public
	 */

	public final  function RenvoyerDepense() {

	}


}
?>