<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class TCConditionMultiplicateur {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $conditionMultiplicateurFormatee;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $avoirMultiplicateur = false;

	/**
	 * simple, x3minimum
	 * @var string
	 * @access private
	 */
	private  $typeMultiplicateur;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $valeurMultiplicateur;


	/**
	 * @access public
	 * @param MessageDemande $messageDemande 
	 * @return void
	 */

	public final  function __construct(MessageDemande $messageDemande) {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DecomposerMessageDemande() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function ComposerMessageJeu() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherAvoirMultiplicateur() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTypeMultiplicateur() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherValeurMultiplicateur() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherTexteDescription() {

	}


	/**
	 * @access public
	 * @return TCConditionMultiplicateur[]
	 */

	public final  function RechercherConditionsMultiplicateur() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function ComposerTexteDescription() {

	}


}
?>