<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class TCConditionPeriode {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $nombreTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $dateJeuFormatee;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $periodeJeuFormatee;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $texteDescription;


	/**
	 * @access public
	 * @param string $conditionPeriode 
	 * @return void
	 */

	public abstract  function __construct($conditionPeriode) ;

	/**
	 * @access public
	 * @return void
	 */

	public final  function ExtraireDemandePeriode() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public abstract  function ConstruireDateJeuFormatee() ;

	/**
	 * @access public
	 * @return string
	 */

	public abstract  function ConstruirePeriodeFormatee() ;

	/**
	 * @access public
	 * @return void
	 */

	public abstract  function ConstruireTexteDescription() ;

	/**
	 * @access public
	 * @return string
	 */

	public final  function RenvoyerConditionPeriode() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateJeu() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNombreTirage() {

	}


}
?>