<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class TechniqueComposee {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nom;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $variante;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $version;

	/**
	 * 
	 * @var MessageDemande
	 * @access private
	 */
	private  $messageDemande;

	/**
	 * 
	 * @var datetime
	 * @access private
	 */
	private  $dateDebut;

	/**
	 * 
	 * @var bool
	 * @access private
	 */
	private  $etrePeriodeMorte;

	/**
	 * 
	 * @var MessageJeu[]
	 * @access private
	 */
	private  $listeMessageJeu;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $niveau;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $jeuNumero;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $jeuGrille;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $jeuPeriode;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $jeuMise;

	/**
	 * 
	 * @var jeu
	 * @access private
	 */
	private  $jeuMultiplicateur;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInformationTechnique() {

	}


	/**
	 * @access public
	 * @return MessageDemande
	 */

	public final  function RechercherMessageDemande() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherTiragePasse() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherTirageJouee() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateDebut() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RechercherEtatPeriodeMorte() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNombreGrilleJouee() {

	}


	/**
	 * @access public
	 * @return bool
	 */

	public final  function RchercherAutorisationJeu() {

	}


	/**
	 * @access public
	 * @return void
	 */

	public final  function DecomposerMessageDemande() {

	}


	/**
	 * @access public
	 * @return MessageJeu
	 */

	public final  function ComposerMessageJeu() {

	}


}
?>