<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Tirage {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $identifiant;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $numeroTirage;

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $dateJeu;

	/**
	 * 
	 * @var int[]
	 * @access private
	 */
	private  $listeNumeroSorti;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $valeurMultiplicateur;

	/**
	 * 
	 * @var Jeu
	 * @access private
	 */
	private  $observateurTirage;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $momentTirage;

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $dateForclusion;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $numeroJackpot;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $montantJackpot;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $numeroJokerplus;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $devis;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee = false) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInfoTirage() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherNumeroTirage() {

	}


	/**
	 * @access public
	 * @return datetime
	 */

	public final  function RechercherDateJeu() {

	}


	/**
	 * @access public
	 * @return int[]
	 */

	public final  function RechercherNumerosSortis() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherMultiplicateur() {

	}


	/**
	 * @access public
	 * @return Jeu
	 */

	public final  function RechercherObservateur() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherMomentTirage() {

	}


	/**
	 * @access public
	 * @return date
	 */

	public final  function RechercherDateForclusion() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherJackpot() {

	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function RechercherJokerplus() {

	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function RechercherDevise() {

	}


}
?>