<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Versement {

	/**
	 * 
	 * @var Utilisateur
	 * @access private
	 */
	private  $utilisateur;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $numeroVersement;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $fichier;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $moyenPaiement;

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $creditConverti;

	/**
	 * 
	 * @var float
	 * @access private
	 */
	private  $sommePaye;

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $dateVersement;


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function __construct($listeDonnee) {

	}


	/**
	 * @access public
	 * @param array $listeDonnee 
	 * @return void
	 */

	public final  function Hydrateur($listeDonnee) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public final  function RechercherInfoVersement() {

	}


}
?>